spring.application.name=jpabackend

spring.datasource.url=jdbc:postgresql://localhost:5433/jpabackend
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

loan.interest.annual-rate=0.12